baseURL = "https://tw-shift-schedule.firebaseapp.com/"
languageCode = "zh-Hant"
title = "班表小幫手"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "班表小幫手"
    description = "免費、容易使用的工時檢測工具"
    email = ""
    phone = "g0v slack #labor 頻道"
    address = "社群：g0v slack #labor 頻道"
    year = 2018
    background = ""
    favicon = "favicon2.ico"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = true

    footerEnableContact = false
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = false
[[menu.main]]
    name = "記錄工時"
    url = "/"
    weight = 1
[[menu.main]]
    name = "法令追蹤"
    url = "/"
    weight = 2
[[menu.main]]
    name = "班表分析"
    url = "/post/"
    weight = 3
[[menu.main]]
    name = "規劃班表"
    url = "/"
    weight = 4

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "UA-125868672-1"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fa-facebook-square"
    footer = false
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fa-twitter-square"
    footer = false
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/g0v/tw-shift-schedule"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:poga.po@gmail.com"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"
